services:
  uevent-postgres:
    image: postgres:15
    container_name: uevent-postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "6868:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
