openapi: 3.1.1
info:
  title: uevent user-svc API
  description: API documentation for uevent
  version: 0.1.0

servers:
  - url: http://localhost:6767

paths:
  /uevent/v1/account/registration/:
    $ref: './spec/auth/paths/Registration.yaml'
  /uevent/v1/account/registration/admin:
    $ref: './spec/auth/paths/RegistrationByAdmin.yaml'

  /uevent/v1/account/login:
    $ref: './spec/auth/paths/LoginByEmail.yaml'
  /uevent/v1/account/login/google:
    $ref: './spec/auth/paths/LoginByGoogle.yaml'
  /uevent/v1/account/login/google/callback:
    $ref: './spec/auth/paths/LoginByGoogleCallback.yaml'

  /uevent/v1/account/refresh:
    $ref: './spec/auth/paths/Refresh.yaml'
  /uevent/v1/account/logout:
    $ref: './spec/auth/paths/Logout.yaml'
  /uevent/v1/account/me:
    $ref: './spec/auth/paths/MyAccount.yaml'

  /uevent/v1/profiles/:
    $ref: './spec/profile/paths/FilterProfiles.yaml'
  /uevent/v1/profiles/me:
    $ref: './spec/profile/paths/MyProfile.yaml'
  /uevent/v1/profiles/me/avatar:
    $ref: './spec/profile/paths/MyProfileAvatar.yaml'
  /uevent/v1/profiles/{account_id}:
    $ref: './spec/profile/paths/ProfileById.yaml'
  /uevent/v1/profiles/@{username}:
    $ref: './spec/profile/paths/ProfileByUsername.yaml'

  /uevent/v1/company:
    $ref: './spec/company/paths/Companies.yaml'
  /uevent/v1/company/{id}:
    $ref: './spec/company/paths/CompanyById.yaml'
  /uevent/v1/company/{id}/avatar:
    $ref: './spec/company/paths/CompanyAvatar.yaml'
  /uevent/v1/company/{id}/banner:
    $ref: './spec/company/paths/CompanyBanner.yaml'
  /uevent/v1/company/subscriptions:
    $ref: './spec/company/paths/MySubscriptions.yaml'
  /uevent/v1/company/{id}/subscribers:
    $ref: './spec/company/paths/CompanySubscribers.yaml'
  /uevent/v1/company/{id}/subscribe:
    $ref: './spec/company/paths/CompanySubscribe.yaml'



  /uevent/v1/event:
    $ref: './spec/event/paths/Events.yaml'
  /uevent/v1/event/{id}:
    $ref: './spec/event/paths/GetEventById.yaml'

  /uevent/v1/tag:
    $ref: './spec/tag/paths/Tags.yaml'
  /uevent/v1/tag/{id}:
    $ref: './spec/tag/paths/TagById.yaml'

  /uevent/v1/news:
    $ref: './spec/news/paths/News.yaml'
  /uevent/v1/news/{id}:
    $ref: './spec/news/paths/NewsById.yaml'


components:
  schemas:
    #auth
    LoginByEmail:
      $ref: './spec/auth/schemas/LoginByEmail.yaml'
    Registration:
      $ref: './spec/auth/schemas/Registration.yaml'
    RegistrationAdmin:
      $ref: './spec/auth/schemas/RegistrationAdmin.yaml'

    Account:
      $ref: './spec/auth/schemas/Account.yaml'

    #profile
    UpdateProfile:
      $ref: './spec/profile/schemas/UpdateProfile.yaml'

    Profile:
      $ref: './spec/profile/schemas/Profile.yaml'
    ProfileData:
      $ref: './spec/profile/schemas/ProfileData.yaml'
    ProfilesCollection:
      $ref: './spec/profile/schemas/ProfilesCollection.yaml'

    #company
    Company:
      $ref: './spec/company/schemas/Company.yaml'
    CompanyData:
      $ref: './spec/company/schemas/CompanyData.yaml'
    CompaniesCollection:
      $ref: './spec/company/schemas/CompaniesCollection.yaml'
    CompanyCreate:
      $ref: './spec/company/schemas/CompanyCreate.yaml'
    CompanyUpdate:
      $ref: './spec/company/schemas/CompanyUpdate.yaml'
    CompanySub:
      $ref: './spec/company/schemas/CompanySub.yaml'
    CompanySubscribersCollection:
      $ref: './spec/company/schemas/CompanySubscribersCollection.yaml'

    #event
    Event:
      $ref: './spec/event/schemas/Event.yaml'
    EventData:
      $ref: './spec/event/schemas/EventData.yaml'
    EventsCollection:
      $ref: './spec/event/schemas/EventsCollection.yaml'
    EventCreate:
      $ref: './spec/event/schemas/EventCreate.yaml'

    #tag
    Tag:
      $ref: './spec/tag/schemas/Tag.yaml'
    TagData:
      $ref: './spec/tag/schemas/TagData.yaml'
    TagsCollection:
      $ref: './spec/tag/schemas/TagsCollection.yaml'
    TagCreate:
      $ref: './spec/tag/schemas/TagCreate.yaml'
    TagUpdate:
      $ref: './spec/tag/schemas/TagUpdate.yaml'

    #news
    News:
      $ref: './spec/news/schemas/News.yaml'
    NewsData:
      $ref: './spec/news/schemas/NewsData.yaml'
    NewsCollection:
      $ref: './spec/news/schemas/NewsCollection.yaml'
    NewsCreate:
      $ref: './spec/news/schemas/NewsCreate.yaml'
    NewsUpdate:
      $ref: './spec/news/schemas/NewsUpdate.yaml'
